
#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["sophisticatedbackpacks:blasting_upgrade|true", "sophisticatedbackpacks:iron_backpack|true", "sophisticatedbackpacks:auto_smoking_upgrade|true", "sophisticatedbackpacks:gold_backpack|true", "sophisticatedbackpacks:copper_backpack|true", "sophisticatedbackpacks:advanced_deposit_upgrade|true", "sophisticatedbackpacks:advanced_void_upgrade|true", "sophisticatedbackpacks:restock_upgrade|true", "sophisticatedbackpacks:stonecutter_upgrade|true", "sophisticatedbackpacks:advanced_compacting_upgrade|true", "sophisticatedbackpacks:backpack|true", "sophisticatedbackpacks:pump_upgrade|true", "sophisticatedbackpacks:tool_swapper_upgrade|true", "sophisticatedbackpacks:feeding_upgrade|true"]

